services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.rag.rule=Host(`rag.saifdamra.com`)
      - traefik.http.routers.rag.entrypoints=websecure
      - traefik.http.routers.rag.tls.certresolver=letsencrypt
      - traefik.http.services.rag.loadbalancer.server.port=8000
